# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir mcp[cli]>=1.6.0 httpx>=0.28.1

# Copy application source
COPY main.py /app/main.py
COPY README.md LICENSE /app/

# Expose no ports (uses stdio)

# Default command to run the MCP server
CMD ["python", "main.py"]
